import {
  Gym,
  User,
  Member,
  MembershipPlan,
  PaymentRecord,
  AttendanceRecord,
  Trainer,
  WorkoutPlan,
  DietPlan,
  ProgressRecord,
  StaffMember,
  AuditLog,
  AppNotification,
  WhatsAppTemplate,
} from '../types';

export const INITIAL_GYMS: Gym[] = [
  {
    id: 'gym-powerfit-01',
    name: 'PowerFit Fitness Club',
    slug: 'powerfit',
    ownerId: 'user-owner-01',
    ownerName: 'Rajesh Patel',
    ownerEmail: 'owner@example.com',
    ownerPhone: '+91 98765 43210',
    createdAt: '2025-01-10T10:00:00Z',
    status: 'active',
    isOnboarded: true,
    subscription: {
      id: 'sub-01',
      gymId: 'gym-powerfit-01',
      tier: 'growth',
      status: 'active',
      pricePerMonth: 1999,
      maxMembers: 2000,
      startDate: '2026-01-01',
      endDate: '2027-01-01',
      autoRenew: true,
    },
    settings: {
      name: 'PowerFit Fitness Club',
      tagline: 'Run Your Gym. Grow Your Members.',
      logoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=150&auto=format&fit=crop&q=80',
      address: 'Plot 42, 100ft Road, Indiranagar, Bengaluru, Karnataka 560038',
      phone: '+91 98765 43210',
      email: 'contact@powerfitgym.in',
      website: 'https://powerfitgym.in',
      gstNumber: '29ABCDE1234F1Z5',
      currency: 'INR',
      currencySymbol: '₹',
      timezone: 'Asia/Kolkata',
      receiptPrefix: 'REC',
      memberIdPrefix: 'FIT',
      expiringSoonDays: 7,
      duplicateAttendanceMinutes: 60,
      enableQrAttendance: true,
      theme: 'light',
    },
  },
  {
    id: 'gym-ironforge-02',
    name: 'IronForge Strength & CrossFit',
    slug: 'ironforge',
    ownerId: 'user-iron-02',
    ownerName: 'Vikramaditya Rathore',
    ownerEmail: 'vikram@ironforge.in',
    ownerPhone: '+91 98111 22233',
    createdAt: '2025-06-15T11:30:00Z',
    status: 'active',
    isOnboarded: true,
    subscription: {
      id: 'sub-02',
      gymId: 'gym-ironforge-02',
      tier: 'pro',
      status: 'active',
      pricePerMonth: 3999,
      maxMembers: -1,
      startDate: '2026-02-01',
      endDate: '2027-02-01',
      autoRenew: true,
    },
    settings: {
      name: 'IronForge Strength & CrossFit',
      tagline: 'Forging Unbreakable Champions',
      logoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=150&auto=format&fit=crop&q=80',
      address: '7th Sector, HSR Layout, Bengaluru, Karnataka 560102',
      phone: '+91 98111 22233',
      email: 'support@ironforge.in',
      website: 'https://ironforge.in',
      gstNumber: '29AABCI5432K1Z9',
      currency: 'INR',
      currencySymbol: '₹',
      timezone: 'Asia/Kolkata',
      receiptPrefix: 'IFR',
      memberIdPrefix: 'IFM',
      expiringSoonDays: 7,
      duplicateAttendanceMinutes: 45,
      enableQrAttendance: true,
      theme: 'dark',
    },
  },
  {
    id: 'gym-zenith-03',
    name: 'Zenith Wellness & Spa',
    slug: 'zenith',
    ownerId: 'user-zenith-03',
    ownerName: 'Meera Deshmukh',
    ownerEmail: 'meera@zenithwellness.com',
    ownerPhone: '+91 97222 33344',
    createdAt: '2026-08-20T09:15:00Z',
    status: 'trial',
    isOnboarded: true,
    subscription: {
      id: 'sub-03',
      gymId: 'gym-zenith-03',
      tier: 'starter',
      status: 'trial',
      pricePerMonth: 999,
      maxMembers: 500,
      startDate: '2026-08-20',
      endDate: '2026-09-20',
      autoRenew: false,
    },
    settings: {
      name: 'Zenith Wellness & Spa',
      tagline: 'Holistic Body & Mind Renewal',
      logoUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=150&auto=format&fit=crop&q=80',
      address: 'Bandra West, Mumbai, Maharashtra 400050',
      phone: '+91 97222 33344',
      email: 'hello@zenithwellness.com',
      website: 'https://zenithwellness.com',
      currency: 'INR',
      currencySymbol: '₹',
      timezone: 'Asia/Kolkata',
      receiptPrefix: 'ZNR',
      memberIdPrefix: 'ZNM',
      expiringSoonDays: 5,
      duplicateAttendanceMinutes: 60,
      enableQrAttendance: true,
      theme: 'light',
    },
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-superadmin-01',
    email: 'admin@example.com',
    name: 'Shubhanshu Jain',
    phone: '+91 99999 00000',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-01T00:00:00Z',
    status: 'active',
  },
  {
    id: 'user-owner-01',
    email: 'owner@example.com',
    name: 'Rajesh Patel',
    phone: '+91 98765 43210',
    role: 'gym_owner',
    gymId: 'gym-powerfit-01',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T10:00:00Z',
    status: 'active',
  },
  {
    id: 'user-staff-01',
    email: 'staff@example.com',
    name: 'Priya Nair',
    phone: '+91 98450 11223',
    role: 'staff',
    gymId: 'gym-powerfit-01',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: [
      'members_view',
      'members_add',
      'members_edit',
      'attendance',
      'payments',
      'memberships',
      'whatsapp',
      'reports',
    ],
    createdAt: '2025-02-01T09:00:00Z',
    status: 'active',
  },
  {
    id: 'user-member-01',
    email: 'member@example.com',
    name: 'Rahul Sharma',
    phone: '+91 98201 54321',
    role: 'member',
    gymId: 'gym-powerfit-01',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-03-01T10:30:00Z',
    status: 'active',
  },
];

export const INITIAL_PLANS: MembershipPlan[] = [
  {
    id: 'plan-monthly',
    gymId: 'gym-powerfit-01',
    name: 'Monthly Classic',
    durationMonths: 1,
    durationDays: 30,
    price: 1500,
    description: 'Full gym floor access, cardio equipment & locker facilities for 1 month.',
    accessType: 'gym_only',
    ptSessionsIncluded: 0,
    freezeDaysAllowed: 0,
    isActive: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'plan-quarterly',
    gymId: 'gym-powerfit-01',
    name: 'Quarterly Fitness',
    durationMonths: 3,
    durationDays: 90,
    price: 4000,
    description: '3 months gym & cardio access + 1 complimentary personal training orientation.',
    accessType: 'all_access',
    ptSessionsIncluded: 1,
    freezeDaysAllowed: 7,
    isActive: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'plan-half-yearly',
    gymId: 'gym-powerfit-01',
    name: 'Half-Yearly Transform',
    durationMonths: 6,
    durationDays: 180,
    price: 7000,
    description: '6 months complete access + 3 PT sessions + 15 days membership freeze flexibility.',
    accessType: 'all_access',
    ptSessionsIncluded: 3,
    freezeDaysAllowed: 15,
    isActive: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'plan-yearly',
    gymId: 'gym-powerfit-01',
    name: 'Annual Elite VIP',
    durationMonths: 12,
    durationDays: 365,
    price: 12000,
    description: '1 year unlimited access + steam bath + 6 personal training sessions + 30 days freeze.',
    accessType: 'all_access',
    ptSessionsIncluded: 6,
    freezeDaysAllowed: 30,
    isActive: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'trainer-01',
    gymId: 'gym-powerfit-01',
    name: 'Vikram Singh',
    phone: '+91 98711 55667',
    email: 'vikram.trainer@powerfitgym.in',
    avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=150&auto=format&fit=crop&q=80',
    specialization: 'Strength & Conditioning, Olympic Lifts',
    joiningDate: '2025-01-20',
    status: 'active',
    hourlyRate: 800,
    assignedMemberCount: 14,
    ptRevenue: 48000,
    bio: 'Certified CSCS strength coach with 8+ years experience training athletes and serious lifters.',
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'trainer-02',
    gymId: 'gym-powerfit-01',
    name: 'Ananya Rao',
    phone: '+91 98455 33221',
    email: 'ananya.rao@powerfitgym.in',
    avatarUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=150&auto=format&fit=crop&q=80',
    specialization: 'Yoga, Mobility & Functional Strength',
    joiningDate: '2025-02-10',
    status: 'active',
    hourlyRate: 750,
    assignedMemberCount: 11,
    ptRevenue: 34500,
    bio: 'Specialist in postural correction, core stability, and athletic mobility rehabilitation.',
    createdAt: '2025-02-10T00:00:00Z',
  },
  {
    id: 'trainer-03',
    gymId: 'gym-powerfit-01',
    name: 'Kabir Khan',
    phone: '+91 98200 99887',
    email: 'kabir.khan@powerfitgym.in',
    avatarUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=150&auto=format&fit=crop&q=80',
    specialization: 'CrossFit, HIIT & Calisthenics',
    joiningDate: '2025-03-01',
    status: 'active',
    hourlyRate: 900,
    assignedMemberCount: 9,
    ptRevenue: 36000,
    bio: 'CrossFit Level 2 Trainer focusing on explosive agility, stamina and tactical conditioning.',
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'trainer-04',
    gymId: 'gym-powerfit-01',
    name: 'Neha Sharma',
    phone: '+91 98333 44556',
    email: 'neha.sharma@powerfitgym.in',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    specialization: 'Female Fitness, Fat Loss & Nutrition',
    joiningDate: '2025-04-05',
    status: 'active',
    hourlyRate: 700,
    assignedMemberCount: 12,
    ptRevenue: 37800,
    bio: 'K11 Certified Fitness Instructor specializing in sustainable fat loss and nutritional planning.',
    createdAt: '2025-04-05T00:00:00Z',
  },
  {
    id: 'trainer-05',
    gymId: 'gym-powerfit-01',
    name: 'Rohan Deshmukh',
    phone: '+91 98999 11223',
    email: 'rohan.deshmukh@powerfitgym.in',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    specialization: 'Hypertrophy & Contest Prep',
    joiningDate: '2025-05-15',
    status: 'active',
    hourlyRate: 850,
    assignedMemberCount: 7,
    ptRevenue: 25500,
    bio: 'Gold Medalist State Bodybuilder focusing on muscle building and strict biomechanics.',
    createdAt: '2025-05-15T00:00:00Z',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'staff-01',
    gymId: 'gym-powerfit-01',
    userId: 'user-staff-01',
    name: 'Priya Nair',
    email: 'staff@example.com',
    phone: '+91 98450 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    roleTitle: 'Head Receptionist & Accounts',
    permissions: [
      'members_view',
      'members_add',
      'members_edit',
      'attendance',
      'payments',
      'memberships',
      'whatsapp',
      'reports',
    ],
    status: 'active',
    joiningDate: '2025-02-01',
    createdAt: '2025-02-01T09:00:00Z',
  },
  {
    id: 'staff-02',
    gymId: 'gym-powerfit-01',
    userId: 'user-staff-02',
    name: 'Suresh Yadav',
    email: 'suresh.operations@powerfitgym.in',
    phone: '+91 98888 77665',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    roleTitle: 'Gym Floor & Facility Manager',
    permissions: ['members_view', 'attendance', 'trainers'],
    status: 'active',
    joiningDate: '2025-03-10',
    createdAt: '2025-03-10T09:00:00Z',
  },
];

// Helper to generate dates relative to current date (2026-09-13)
function getOffsetDate(days: number): string {
  const d = new Date('2026-09-13T00:00:00Z');
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

// Generate 52 members with realistic variety across plans, statuses, payments, and activity
const RAW_MEMBERS_DATA = [
  {
    id: 'mem-001',
    code: 'FIT-000001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    gender: 'male' as const,
    phone: '+91 98201 54321',
    email: 'member@example.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-67),
    end: getOffsetDate(23), // 23 days remaining -> Active
    price: 4000,
    paid: 4000,
    trainerId: 'trainer-01',
    trainerName: 'Vikram Singh',
    lastVisit: getOffsetDate(0), // visited today
    visits: 48,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    notes: 'Goal: Lean mass gain. Strict attendee.',
  },
  {
    id: 'mem-002',
    code: 'FIT-000002',
    firstName: 'Amit',
    lastName: 'Verma',
    gender: 'male' as const,
    phone: '+91 98190 22334',
    email: 'amit.v@gmail.com',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-28),
    end: getOffsetDate(2), // 2 days remaining -> Expiring Soon
    price: 1500,
    paid: 1500,
    trainerId: 'trainer-01',
    trainerName: 'Vikram Singh',
    lastVisit: getOffsetDate(-1),
    visits: 19,
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-003',
    code: 'FIT-000003',
    firstName: 'Sneha',
    lastName: 'Patil',
    gender: 'female' as const,
    phone: '+91 97654 88990',
    email: 'sneha.patil@outlook.com',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    months: 12,
    start: getOffsetDate(-120),
    end: getOffsetDate(245),
    price: 12000,
    paid: 10000, // pending 2000
    trainerId: 'trainer-04',
    trainerName: 'Neha Sharma',
    lastVisit: getOffsetDate(-2),
    visits: 84,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    notes: 'Partial payment pending balance ₹2,000.',
  },
  {
    id: 'mem-004',
    code: 'FIT-000004',
    firstName: 'Karan',
    lastName: 'Malhotra',
    gender: 'male' as const,
    phone: '+91 98112 33445',
    email: 'karan.m@gmail.com',
    planId: 'plan-half-yearly',
    planName: 'Half-Yearly Transform',
    months: 6,
    start: getOffsetDate(-190),
    end: getOffsetDate(-10), // Expired 10 days ago!
    price: 7000,
    paid: 7000,
    trainerId: 'trainer-03',
    trainerName: 'Kabir Khan',
    lastVisit: getOffsetDate(-12),
    visits: 62,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-005',
    code: 'FIT-000005',
    firstName: 'Pooja',
    lastName: 'Reddy',
    gender: 'female' as const,
    phone: '+91 98490 55667',
    email: 'pooja.r@gmail.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-85),
    end: getOffsetDate(5), // 5 days remaining -> Expiring Soon
    price: 4000,
    paid: 3000, // pending 1000
    trainerId: 'trainer-02',
    trainerName: 'Ananya Rao',
    lastVisit: getOffsetDate(-5),
    visits: 35,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-006',
    code: 'FIT-000006',
    firstName: 'Vikram',
    lastName: 'Desai',
    gender: 'male' as const,
    phone: '+91 98230 44556',
    email: 'vikram.desai@yahoo.com',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-35),
    end: getOffsetDate(-5), // Expired 5 days ago!
    price: 1500,
    paid: 1500,
    trainerId: 'trainer-05',
    trainerName: 'Rohan Deshmukh',
    lastVisit: getOffsetDate(-16), // At risk: 16 days no visit!
    visits: 9,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-007',
    code: 'FIT-000007',
    firstName: 'Deepak',
    lastName: 'Chopra',
    gender: 'male' as const,
    phone: '+91 98310 11229',
    email: 'deepak.c@hotmail.com',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    months: 12,
    start: getOffsetDate(-60),
    end: getOffsetDate(305),
    price: 12000,
    paid: 12000,
    trainerId: 'trainer-01',
    trainerName: 'Vikram Singh',
    lastVisit: getOffsetDate(0),
    visits: 54,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-008',
    code: 'FIT-000008',
    firstName: 'Divya',
    lastName: 'Krishnan',
    gender: 'female' as const,
    phone: '+91 98401 77665',
    email: 'divya.k@gmail.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-45),
    end: getOffsetDate(45),
    price: 4000,
    paid: 4000,
    trainerId: 'trainer-02',
    trainerName: 'Ananya Rao',
    lastVisit: getOffsetDate(-1),
    visits: 31,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-009',
    code: 'FIT-000009',
    firstName: 'Rohan',
    lastName: 'Mehta',
    gender: 'male' as const,
    phone: '+91 98920 66778',
    email: 'rohan.m@gmail.com',
    planId: 'plan-half-yearly',
    planName: 'Half-Yearly Transform',
    months: 6,
    start: getOffsetDate(-10),
    end: getOffsetDate(170),
    price: 7000,
    paid: 4000, // pending 3000
    trainerId: 'trainer-03',
    trainerName: 'Kabir Khan',
    lastVisit: getOffsetDate(-1),
    visits: 8,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'mem-010',
    code: 'FIT-000010',
    firstName: 'Aakash',
    lastName: 'Joshi',
    gender: 'male' as const,
    phone: '+91 98220 99112',
    email: 'aakash.j@gmail.com',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-29),
    end: getOffsetDate(1), // 1 day remaining -> Expiring Soon
    price: 1500,
    paid: 1500,
    lastVisit: getOffsetDate(-3),
    visits: 14,
  },
  {
    id: 'mem-011',
    code: 'FIT-000011',
    firstName: 'Neha',
    lastName: 'Kulkarni',
    gender: 'female' as const,
    phone: '+91 98601 22334',
    email: 'neha.k@gmail.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-70),
    end: getOffsetDate(20),
    price: 4000,
    paid: 4000,
    trainerId: 'trainer-04',
    trainerName: 'Neha Sharma',
    lastVisit: getOffsetDate(-2),
    visits: 28,
  },
  {
    id: 'mem-012',
    code: 'FIT-000012',
    firstName: 'Manish',
    lastName: 'Pandey',
    gender: 'male' as const,
    phone: '+91 98101 44556',
    email: 'manish.p@yahoo.co.in',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-40),
    end: getOffsetDate(-10), // Expired
    price: 1500,
    paid: 1000, // pending 500!
    lastVisit: getOffsetDate(-15),
    visits: 11,
  },
  {
    id: 'mem-013',
    code: 'FIT-000013',
    firstName: 'Siddharth',
    lastName: 'Rao',
    gender: 'male' as const,
    phone: '+91 98450 77889',
    email: 'sid.rao@gmail.com',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    months: 12,
    start: getOffsetDate(-180),
    end: getOffsetDate(185),
    price: 12000,
    paid: 12000,
    trainerId: 'trainer-01',
    trainerName: 'Vikram Singh',
    lastVisit: getOffsetDate(0),
    visits: 120,
  },
  {
    id: 'mem-014',
    code: 'FIT-000014',
    firstName: 'Ananya',
    lastName: 'Sen',
    gender: 'female' as const,
    phone: '+91 98300 88776',
    email: 'ananya.sen@gmail.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-88),
    end: getOffsetDate(2), // 2 days remaining -> Expiring Soon
    price: 4000,
    paid: 4000,
    trainerId: 'trainer-02',
    trainerName: 'Ananya Rao',
    lastVisit: getOffsetDate(-4),
    visits: 38,
  },
  {
    id: 'mem-015',
    code: 'FIT-000015',
    firstName: 'Gaurav',
    lastName: 'Bhatia',
    gender: 'male' as const,
    phone: '+91 98180 55443',
    email: 'gaurav.b@gmail.com',
    planId: 'plan-half-yearly',
    planName: 'Half-Yearly Transform',
    months: 6,
    start: getOffsetDate(-120),
    end: getOffsetDate(60),
    price: 7000,
    paid: 7000,
    trainerId: 'trainer-05',
    trainerName: 'Rohan Deshmukh',
    lastVisit: getOffsetDate(-1),
    visits: 76,
  },
  {
    id: 'mem-016',
    code: 'FIT-000016',
    firstName: 'Ishaan',
    lastName: 'Kapoor',
    gender: 'male' as const,
    phone: '+91 98200 44332',
    email: 'ishaan.k@gmail.com',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-5),
    end: getOffsetDate(25),
    price: 1500,
    paid: 1500,
    lastVisit: getOffsetDate(0),
    visits: 4,
  },
  {
    id: 'mem-017',
    code: 'FIT-000017',
    firstName: 'Ritu',
    lastName: 'Aggarwal',
    gender: 'female' as const,
    phone: '+91 98119 22331',
    email: 'ritu.a@yahoo.com',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    months: 3,
    start: getOffsetDate(-100),
    end: getOffsetDate(-10), // Expired
    price: 4000,
    paid: 4000,
    trainerId: 'trainer-04',
    trainerName: 'Neha Sharma',
    lastVisit: getOffsetDate(-25),
    visits: 21,
  },
  {
    id: 'mem-018',
    code: 'FIT-000018',
    firstName: 'Sanjay',
    lastName: 'Singhania',
    gender: 'male' as const,
    phone: '+91 98211 66554',
    email: 'sanjay.s@gmail.com',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    months: 12,
    start: getOffsetDate(-30),
    end: getOffsetDate(335),
    price: 12000,
    paid: 8000, // pending 4000
    trainerId: 'trainer-01',
    trainerName: 'Vikram Singh',
    lastVisit: getOffsetDate(-1),
    visits: 24,
  },
  {
    id: 'mem-019',
    code: 'FIT-000019',
    firstName: 'Tara',
    lastName: 'Banerjee',
    gender: 'female' as const,
    phone: '+91 98319 44332',
    email: 'tara.b@gmail.com',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    months: 1,
    start: getOffsetDate(-26),
    end: getOffsetDate(4), // Expiring soon in 4 days
    price: 1500,
    paid: 1500,
    lastVisit: getOffsetDate(-3),
    visits: 12,
  },
  {
    id: 'mem-020',
    code: 'FIT-000020',
    firstName: 'Aditya',
    lastName: 'Nambiar',
    gender: 'male' as const,
    phone: '+91 98470 11998',
    email: 'aditya.n@gmail.com',
    planId: 'plan-half-yearly',
    planName: 'Half-Yearly Transform',
    months: 6,
    start: getOffsetDate(-150),
    end: getOffsetDate(30),
    price: 7000,
    paid: 7000,
    trainerId: 'trainer-03',
    trainerName: 'Kabir Khan',
    lastVisit: getOffsetDate(-2),
    visits: 89,
  },
];

// Expand to 50 members by generating supplementary realistic profiles
for (let i = 21; i <= 52; i++) {
  const codeNum = String(i).padStart(6, '0');
  const firstNames = ['Varun', 'Naveen', 'Simran', 'Akash', 'Kavita', 'Manoj', 'Bhavna', 'Harsh', 'Radhika', 'Tarun', 'Shweta', 'Prateek', 'Meghna', 'Vivek', 'Tanvi', 'Chetan'];
  const lastNames = ['Gupta', 'Iyer', 'Saxena', 'Choudhury', 'Pillai', 'Menon', 'Nath', 'Khatri', 'Dubey', 'Trivedi', 'Bose', 'Gowda', 'Shetty', 'Bhat', 'Dutta', 'Pandit'];
  const fn = firstNames[i % firstNames.length];
  const ln = lastNames[i % lastNames.length];
  const isFemale = ['Simran', 'Kavita', 'Bhavna', 'Radhika', 'Shweta', 'Meghna', 'Tanvi'].includes(fn);
  
  // Vary expiry
  let offsetEnd = 0;
  if (i % 7 === 0) offsetEnd = -Math.floor(i % 15); // expired
  else if (i % 5 === 0) offsetEnd = Math.floor(i % 6) + 1; // expiring soon
  else offsetEnd = (i * 7) % 200 + 10; // active

  const plans = [
    { id: 'plan-monthly', name: 'Monthly Classic', price: 1500, m: 1 },
    { id: 'plan-quarterly', name: 'Quarterly Fitness', price: 4000, m: 3 },
    { id: 'plan-half-yearly', name: 'Half-Yearly Transform', price: 7000, m: 6 },
    { id: 'plan-yearly', name: 'Annual Elite VIP', price: 12000, m: 12 },
  ];
  const selectedPlan = plans[i % plans.length];
  const startOffset = offsetEnd - (selectedPlan.m * 30);
  const isPending = i % 8 === 0;
  const paid = isPending ? selectedPlan.price - 1000 : selectedPlan.price;

  RAW_MEMBERS_DATA.push({
    id: `mem-${String(i).padStart(3, '0')}`,
    code: `FIT-${codeNum}`,
    firstName: fn,
    lastName: ln,
    gender: isFemale ? 'female' : 'male',
    phone: `+91 ${98000 + (i * 37)} ${10000 + (i * 71)}`,
    email: `${fn.toLowerCase()}.${ln.toLowerCase()}@example.com`,
    planId: selectedPlan.id,
    planName: selectedPlan.name,
    months: selectedPlan.m,
    start: getOffsetDate(startOffset),
    end: getOffsetDate(offsetEnd),
    price: selectedPlan.price,
    paid: paid,
    trainerId: i % 3 === 0 ? 'trainer-01' : i % 3 === 1 ? 'trainer-02' : undefined,
    trainerName: i % 3 === 0 ? 'Vikram Singh' : i % 3 === 1 ? 'Ananya Rao' : undefined,
    lastVisit: i % 9 === 0 ? undefined : getOffsetDate(-(i % 12)),
    visits: (i * 3) % 70 + 5,
    avatar: undefined,
    notes: undefined,
  });
}

export const INITIAL_MEMBERS: Member[] = RAW_MEMBERS_DATA.map((item) => {
  const daysRem = Math.ceil((new Date(item.end).getTime() - new Date('2026-09-13').getTime()) / (1000 * 60 * 60 * 24));
  let status: Member['status'] = 'active';
  if (daysRem < 0) status = 'expired';
  else if (daysRem <= 7) status = 'expiring_soon';

  return {
    id: item.id,
    gymId: 'gym-powerfit-01',
    memberCode: item.code,
    firstName: item.firstName,
    lastName: item.lastName,
    avatarUrl: item.avatar,
    gender: item.gender,
    dateOfBirth: '1995-05-15',
    phone: item.phone,
    whatsappNumber: item.phone.replace(/[^0-9]/g, ''),
    email: item.email,
    address: 'Indiranagar, Bengaluru',
    emergencyContactName: 'Family Member',
    emergencyContactRelation: 'Spouse/Parent',
    emergencyContactPhone: '+91 99000 88000',
    notes: item.notes,
    referralSource: 'Walk-in / Instagram',
    currentPlanId: item.planId,
    currentPlanName: item.planName,
    membershipStartDate: item.start,
    membershipEndDate: item.end,
    durationMonths: item.months,
    membershipPrice: item.price,
    discount: 0,
    finalAmount: item.price,
    totalPaid: item.paid,
    balanceDue: Math.max(0, item.price - item.paid),
    primaryTrainerId: item.trainerId,
    primaryTrainerName: item.trainerName,
    status,
    isArchived: false,
    lastVisitDate: item.lastVisit,
    totalVisits: item.visits,
    createdAt: `${item.start}T10:00:00Z`,
    updatedAt: `${item.start}T10:00:00Z`,
  };
});

// Initial Payments
export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000001',
    memberId: 'mem-001',
    memberName: 'Rahul Sharma',
    memberCode: 'FIT-000001',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    amount: 4000,
    paymentMethod: 'upi',
    paymentDate: getOffsetDate(-67),
    referenceNumber: 'UPI/923841029/HDFC',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 0,
    status: 'completed',
    createdAt: `${getOffsetDate(-67)}T10:30:00Z`,
  },
  {
    id: 'pay-002',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000002',
    memberId: 'mem-002',
    memberName: 'Amit Verma',
    memberCode: 'FIT-000002',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    amount: 1500,
    paymentMethod: 'cash',
    paymentDate: getOffsetDate(-28),
    referenceNumber: 'CASH-REC-02',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 0,
    status: 'completed',
    createdAt: `${getOffsetDate(-28)}T11:15:00Z`,
  },
  {
    id: 'pay-003',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000003',
    memberId: 'mem-003',
    memberName: 'Sneha Patil',
    memberCode: 'FIT-000003',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    amount: 10000,
    paymentMethod: 'card',
    paymentDate: getOffsetDate(-120),
    referenceNumber: 'CARD-TXN-4921',
    collectedByUserId: 'user-owner-01',
    collectedByUserName: 'Rajesh Patel',
    balanceRemaining: 2000,
    notes: 'Part payment done. Balance 2000 due within 30 days.',
    status: 'completed',
    createdAt: `${getOffsetDate(-120)}T16:00:00Z`,
  },
  {
    id: 'pay-004',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000004',
    memberId: 'mem-005',
    memberName: 'Pooja Reddy',
    memberCode: 'FIT-000005',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    amount: 3000,
    paymentMethod: 'upi',
    paymentDate: getOffsetDate(-85),
    referenceNumber: 'UPI/772391002/GPAY',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 1000,
    status: 'completed',
    createdAt: `${getOffsetDate(-85)}T14:20:00Z`,
  },
  {
    id: 'pay-005',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000005',
    memberId: 'mem-007',
    memberName: 'Deepak Chopra',
    memberCode: 'FIT-000007',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    amount: 12000,
    paymentMethod: 'bank_transfer',
    paymentDate: getOffsetDate(-60),
    referenceNumber: 'NEFT-ICICI-9921',
    collectedByUserId: 'user-owner-01',
    collectedByUserName: 'Rajesh Patel',
    balanceRemaining: 0,
    status: 'completed',
    createdAt: `${getOffsetDate(-60)}T18:00:00Z`,
  },
  {
    id: 'pay-006',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000006',
    memberId: 'mem-008',
    memberName: 'Divya Krishnan',
    memberCode: 'FIT-000008',
    planId: 'plan-quarterly',
    planName: 'Quarterly Fitness',
    amount: 4000,
    paymentMethod: 'upi',
    paymentDate: getOffsetDate(-45),
    referenceNumber: 'UPI/55123901/PAYTM',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 0,
    status: 'completed',
    createdAt: `${getOffsetDate(-45)}T09:40:00Z`,
  },
  {
    id: 'pay-007',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000007',
    memberId: 'mem-009',
    memberName: 'Rohan Mehta',
    memberCode: 'FIT-000009',
    planId: 'plan-half-yearly',
    planName: 'Half-Yearly Transform',
    amount: 4000,
    paymentMethod: 'cash',
    paymentDate: getOffsetDate(-10),
    referenceNumber: 'CASH-REC-07',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 3000,
    status: 'completed',
    createdAt: `${getOffsetDate(-10)}T17:30:00Z`,
  },
  {
    id: 'pay-008',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000008',
    memberId: 'mem-016',
    memberName: 'Ishaan Kapoor',
    memberCode: 'FIT-000016',
    planId: 'plan-monthly',
    planName: 'Monthly Classic',
    amount: 1500,
    paymentMethod: 'upi',
    paymentDate: getOffsetDate(-5),
    referenceNumber: 'UPI/120938491/BHIM',
    collectedByUserId: 'user-staff-01',
    collectedByUserName: 'Priya Nair',
    balanceRemaining: 0,
    status: 'completed',
    createdAt: `${getOffsetDate(-5)}T12:10:00Z`,
  },
  {
    id: 'pay-009',
    gymId: 'gym-powerfit-01',
    receiptNumber: 'REC-2026-000009',
    memberId: 'mem-018',
    memberName: 'Sanjay Singhania',
    memberCode: 'FIT-000018',
    planId: 'plan-yearly',
    planName: 'Annual Elite VIP',
    amount: 8000,
    paymentMethod: 'card',
    paymentDate: getOffsetDate(-30),
    referenceNumber: 'POS-AXIS-9912',
    collectedByUserId: 'user-owner-01',
    collectedByUserName: 'Rajesh Patel',
    balanceRemaining: 4000,
    status: 'completed',
    createdAt: `${getOffsetDate(-30)}T15:25:00Z`,
  },
];

// Initial Attendance
export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-001',
    memberName: 'Rahul Sharma',
    memberCode: 'FIT-000001',
    date: getOffsetDate(0),
    time: '06:30 AM',
    checkInMethod: 'qr_code',
    staffName: 'Self QR Check-In',
    createdAt: `${getOffsetDate(0)}T06:30:00Z`,
  },
  {
    id: 'att-02',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-007',
    memberName: 'Deepak Chopra',
    memberCode: 'FIT-000007',
    date: getOffsetDate(0),
    time: '07:15 AM',
    checkInMethod: 'manual',
    staffName: 'Priya Nair',
    createdAt: `${getOffsetDate(0)}T07:15:00Z`,
  },
  {
    id: 'att-03',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-013',
    memberName: 'Siddharth Rao',
    memberCode: 'FIT-000013',
    date: getOffsetDate(0),
    time: '07:45 AM',
    checkInMethod: 'qr_code',
    staffName: 'Self QR Check-In',
    createdAt: `${getOffsetDate(0)}T07:45:00Z`,
  },
  {
    id: 'att-04',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-016',
    memberName: 'Ishaan Kapoor',
    memberCode: 'FIT-000016',
    date: getOffsetDate(0),
    time: '08:10 AM',
    checkInMethod: 'manual',
    staffName: 'Priya Nair',
    createdAt: `${getOffsetDate(0)}T08:10:00Z`,
  },
  {
    id: 'att-05',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-001',
    memberName: 'Rahul Sharma',
    memberCode: 'FIT-000001',
    date: getOffsetDate(-1),
    time: '06:40 AM',
    checkInMethod: 'qr_code',
    staffName: 'Self QR Check-In',
    createdAt: `${getOffsetDate(-1)}T06:40:00Z`,
  },
  {
    id: 'att-06',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-002',
    memberName: 'Amit Verma',
    memberCode: 'FIT-000002',
    date: getOffsetDate(-1),
    time: '07:00 AM',
    checkInMethod: 'manual',
    staffName: 'Priya Nair',
    createdAt: `${getOffsetDate(-1)}T07:00:00Z`,
  },
  {
    id: 'att-07',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-008',
    memberName: 'Divya Krishnan',
    memberCode: 'FIT-000008',
    date: getOffsetDate(-1),
    time: '08:00 AM',
    checkInMethod: 'qr_code',
    staffName: 'Self QR Check-In',
    createdAt: `${getOffsetDate(-1)}T08:00:00Z`,
  },
  {
    id: 'att-08',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-009',
    memberName: 'Rohan Mehta',
    memberCode: 'FIT-000009',
    date: getOffsetDate(-1),
    time: '06:15 PM',
    checkInMethod: 'manual',
    staffName: 'Suresh Yadav',
    createdAt: `${getOffsetDate(-1)}T18:15:00Z`,
  },
  {
    id: 'att-09',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-015',
    memberName: 'Gaurav Bhatia',
    memberCode: 'FIT-000015',
    date: getOffsetDate(-1),
    time: '07:00 PM',
    checkInMethod: 'qr_code',
    staffName: 'Self QR Check-In',
    createdAt: `${getOffsetDate(-1)}T19:00:00Z`,
  },
];

// Initial Workouts
export const INITIAL_WORKOUTS: WorkoutPlan[] = [
  {
    id: 'workout-01',
    gymId: 'gym-powerfit-01',
    title: '5-Day Hypertrophy Push / Pull / Legs',
    goal: 'Muscle Building',
    level: 'Intermediate',
    durationWeeks: 8,
    description: 'Optimal volume routine focused on compound movements and progressive overload.',
    assignedMemberIds: ['mem-001', 'mem-007', 'mem-015'],
    assignedByTrainerId: 'trainer-01',
    days: [
      {
        dayName: 'Day 1: Chest & Triceps (Push)',
        exercises: [
          {
            id: 'ex-01',
            name: 'Barbell Flat Bench Press',
            muscleGroup: 'Chest',
            sets: 4,
            reps: '8-10',
            weight: '70 kg',
            restSeconds: 90,
            instructions: 'Keep shoulder blades retracted and drive feet through floor.',
          },
          {
            id: 'ex-02',
            name: 'Incline Dumbbell Press',
            muscleGroup: 'Chest',
            sets: 3,
            reps: '10-12',
            weight: '24 kg',
            restSeconds: 60,
          },
          {
            id: 'ex-03',
            name: 'Cable Chest Flys',
            muscleGroup: 'Chest',
            sets: 3,
            reps: '12-15',
            weight: '15 kg',
            restSeconds: 45,
          },
          {
            id: 'ex-04',
            name: 'Overhead Rope Tricep Extension',
            muscleGroup: 'Arms',
            sets: 4,
            reps: '12',
            weight: '22 kg',
            restSeconds: 45,
          },
        ],
      },
      {
        dayName: 'Day 2: Back & Biceps (Pull)',
        exercises: [
          {
            id: 'ex-05',
            name: 'Conventional Barbell Deadlift',
            muscleGroup: 'Back',
            sets: 3,
            reps: '5',
            weight: '110 kg',
            restSeconds: 120,
          },
          {
            id: 'ex-06',
            name: 'Wide Grip Lat Pulldown',
            muscleGroup: 'Back',
            sets: 4,
            reps: '10-12',
            weight: '55 kg',
            restSeconds: 60,
          },
          {
            id: 'ex-07',
            name: 'Seated Cable Row',
            muscleGroup: 'Back',
            sets: 3,
            reps: '10',
            weight: '50 kg',
            restSeconds: 60,
          },
          {
            id: 'ex-08',
            name: 'Incline Dumbbell Bicep Curls',
            muscleGroup: 'Arms',
            sets: 4,
            reps: '12',
            weight: '12 kg',
            restSeconds: 45,
          },
        ],
      },
      {
        dayName: 'Day 3: Quads, Hamstrings & Calves (Legs)',
        exercises: [
          {
            id: 'ex-09',
            name: 'Barbell Back Squat',
            muscleGroup: 'Legs',
            sets: 4,
            reps: '8-10',
            weight: '90 kg',
            restSeconds: 120,
          },
          {
            id: 'ex-10',
            name: 'Leg Press',
            muscleGroup: 'Legs',
            sets: 3,
            reps: '12',
            weight: '160 kg',
            restSeconds: 90,
          },
          {
            id: 'ex-11',
            name: 'Lying Hamstring Leg Curls',
            muscleGroup: 'Legs',
            sets: 4,
            reps: '12-15',
            weight: '40 kg',
            restSeconds: 60,
          },
          {
            id: 'ex-12',
            name: 'Standing Calf Raises',
            muscleGroup: 'Legs',
            sets: 4,
            reps: '20',
            weight: '50 kg',
            restSeconds: 45,
          },
        ],
      },
    ],
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'workout-02',
    gymId: 'gym-powerfit-01',
    title: 'Fat Burn & Functional Mobility',
    goal: 'Fat Loss',
    level: 'Beginner',
    durationWeeks: 6,
    description: 'High calorie burn, metabolic conditioning, and mobility drill circuit.',
    assignedMemberIds: ['mem-003', 'mem-008'],
    assignedByTrainerId: 'trainer-02',
    days: [
      {
        dayName: 'Full Body Metabolic HIIT',
        exercises: [
          {
            id: 'ex-20',
            name: 'Kettlebell Goblet Squats',
            muscleGroup: 'Legs',
            sets: 3,
            reps: '15',
            weight: '12 kg',
            restSeconds: 45,
          },
          {
            id: 'ex-21',
            name: 'Dumbbell Push Press',
            muscleGroup: 'Shoulders',
            sets: 3,
            reps: '12',
            weight: '7.5 kg',
            restSeconds: 45,
          },
          {
            id: 'ex-22',
            name: 'Rowing Machine Intervals',
            muscleGroup: 'Cardio',
            sets: 5,
            reps: '500m',
            restSeconds: 60,
          },
          {
            id: 'ex-23',
            name: 'Plank Shoulder Taps',
            muscleGroup: 'Core',
            sets: 3,
            reps: '20',
            restSeconds: 30,
          },
        ],
      },
    ],
    createdAt: '2025-02-15T00:00:00Z',
  },
];

// Initial Diets
export const INITIAL_DIETS: DietPlan[] = [
  {
    id: 'diet-01',
    gymId: 'gym-powerfit-01',
    name: 'High Protein Lean Bulk (2400 kcal)',
    goal: 'Muscle Gain',
    targetCalories: 2400,
    targetProtein: 160,
    targetCarbs: 260,
    targetFats: 70,
    assignedMemberIds: ['mem-001', 'mem-007'],
    assignedByTrainerId: 'trainer-01',
    meals: [
      {
        time: '08:00 AM',
        name: 'Breakfast',
        items: ['4 Whole Eggs + 2 Egg Whites Scramble', '2 slices Whole Wheat Toast', '1 Banana', 'Black Coffee'],
        calories: 550,
        proteinGrams: 36,
        carbsGrams: 52,
        fatsGrams: 20,
      },
      {
        time: '11:30 AM',
        name: 'Mid-Morning Snack',
        items: ['1 Scoop Whey Protein with water', '30g Roasted Almonds & Walnuts', '1 Apple'],
        calories: 380,
        proteinGrams: 28,
        carbsGrams: 25,
        fatsGrams: 18,
      },
      {
        time: '01:30 PM',
        name: 'Lunch',
        items: ['150g Grilled Chicken Breast / Paneer', '1.5 cups Brown Rice', '1 Bowl Mixed Green Dal', 'Fresh Salad'],
        calories: 650,
        proteinGrams: 48,
        carbsGrams: 75,
        fatsGrams: 14,
      },
      {
        time: '05:00 PM',
        name: 'Pre-Workout Snack',
        items: ['1 cup Greek Yogurt / Curd', '50g Oats with Berries & Honey'],
        calories: 320,
        proteinGrams: 16,
        carbsGrams: 50,
        fatsGrams: 5,
      },
      {
        time: '08:30 PM',
        name: 'Dinner',
        items: ['150g Fish Fillet or Tofu Stir-Fry', '2 Multigrain Rotis', 'Steamed Broccoli & Bell Peppers'],
        calories: 500,
        proteinGrams: 32,
        carbsGrams: 58,
        fatsGrams: 13,
      },
    ],
    notes: 'Drink minimum 3.5 liters of water daily. Take creatine 5g post workout.',
    createdAt: '2025-01-22T00:00:00Z',
  },
  {
    id: 'diet-02',
    gymId: 'gym-powerfit-01',
    name: 'Vegetarian Calorie Deficit (1700 kcal)',
    goal: 'Weight Loss',
    targetCalories: 1700,
    targetProtein: 110,
    targetCarbs: 180,
    targetFats: 45,
    assignedMemberIds: ['mem-003', 'mem-008'],
    assignedByTrainerId: 'trainer-04',
    meals: [
      {
        time: '08:30 AM',
        name: 'Breakfast',
        items: ['Sprouted Moong & Paneer Chilla', 'Mint Chutney', 'Green Tea'],
        calories: 380,
        proteinGrams: 24,
        carbsGrams: 42,
        fatsGrams: 10,
      },
      {
        time: '01:00 PM',
        name: 'Lunch',
        items: ['150g Low-fat Tofu Bhurji', '1 Multigrain Roti', 'Cucumber & Tomato Salad', '1 bowl Thick Curd'],
        calories: 520,
        proteinGrams: 34,
        carbsGrams: 50,
        fatsGrams: 16,
      },
      {
        time: '05:30 PM',
        name: 'Evening Snack',
        items: ['1 Scoop Plant Protein with warm almond milk', 'Handful roasted Makhana'],
        calories: 250,
        proteinGrams: 25,
        carbsGrams: 22,
        fatsGrams: 4,
      },
      {
        time: '08:00 PM',
        name: 'Dinner',
        items: ['Mixed Vegetable Soya Chunk Soup (100g soya chunks)', '1 bowl Quinoa/Brown Rice Pulao'],
        calories: 550,
        proteinGrams: 27,
        carbsGrams: 66,
        fatsGrams: 15,
      },
    ],
    notes: 'Avoid sugary beverages. Keep salt moderate in evening meal.',
    createdAt: '2025-02-12T00:00:00Z',
  },
];

// Initial Progress Records
export const INITIAL_PROGRESS: ProgressRecord[] = [
  {
    id: 'prog-01',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-001',
    date: getOffsetDate(-60),
    weightKg: 82.5,
    heightCm: 178,
    bmi: 26.0,
    bodyFatPercentage: 21.5,
    chestCm: 99,
    waistCm: 89,
    hipsCm: 98,
    armsCm: 34,
    thighsCm: 56,
    notes: 'Initial assessment upon joining.',
    createdAt: `${getOffsetDate(-60)}T11:00:00Z`,
  },
  {
    id: 'prog-02',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-001',
    date: getOffsetDate(-30),
    weightKg: 80.2,
    heightCm: 178,
    bmi: 25.3,
    bodyFatPercentage: 19.8,
    chestCm: 101,
    waistCm: 86,
    hipsCm: 96,
    armsCm: 35,
    thighsCm: 57,
    notes: 'Month 1 checkup. Good waist reduction, muscle fullness up.',
    createdAt: `${getOffsetDate(-30)}T11:00:00Z`,
  },
  {
    id: 'prog-03',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-001',
    date: getOffsetDate(-2),
    weightKg: 78.4,
    heightCm: 178,
    bmi: 24.7,
    bodyFatPercentage: 17.5,
    chestCm: 103,
    waistCm: 82,
    hipsCm: 95,
    armsCm: 36.5,
    thighsCm: 58,
    notes: 'Month 2 checkup. Significant progress in chest, waist down 7cm total!',
    createdAt: `${getOffsetDate(-2)}T11:00:00Z`,
  },
  {
    id: 'prog-04',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-003',
    date: getOffsetDate(-90),
    weightKg: 68.0,
    heightCm: 162,
    bmi: 25.9,
    bodyFatPercentage: 28.0,
    waistCm: 79,
    hipsCm: 99,
    armsCm: 29,
    notes: 'Initial check-in.',
    createdAt: `${getOffsetDate(-90)}T10:00:00Z`,
  },
  {
    id: 'prog-05',
    gymId: 'gym-powerfit-01',
    memberId: 'mem-003',
    date: getOffsetDate(-10),
    weightKg: 63.5,
    heightCm: 162,
    bmi: 24.2,
    bodyFatPercentage: 24.5,
    waistCm: 73,
    hipsCm: 94,
    armsCm: 28,
    notes: 'Down 4.5 kg, feeling energetic and consistent.',
    createdAt: `${getOffsetDate(-10)}T10:00:00Z`,
  },
];

// Initial Audit Logs
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    gymId: 'gym-powerfit-01',
    userId: 'user-staff-01',
    userName: 'Priya Nair',
    userRole: 'staff',
    action: 'RECORD_PAYMENT',
    entity: 'payment',
    entityId: 'pay-001',
    details: 'Recorded payment of ₹4,000 via UPI for member Rahul Sharma (FIT-000001)',
    timestamp: `${getOffsetDate(-67)}T10:30:00Z`,
  },
  {
    id: 'log-02',
    gymId: 'gym-powerfit-01',
    userId: 'user-owner-01',
    userName: 'Rajesh Patel',
    userRole: 'gym_owner',
    action: 'CREATE_MEMBER',
    entity: 'member',
    entityId: 'mem-001',
    details: 'Created new member Rahul Sharma with Quarterly plan',
    timestamp: `${getOffsetDate(-67)}T10:15:00Z`,
  },
  {
    id: 'log-03',
    gymId: 'gym-powerfit-01',
    userId: 'user-staff-01',
    userName: 'Priya Nair',
    userRole: 'staff',
    action: 'CHECK_IN',
    entity: 'attendance',
    entityId: 'att-01',
    details: 'Member Rahul Sharma checked in via QR code',
    timestamp: `${getOffsetDate(0)}T06:30:00Z`,
  },
  {
    id: 'log-04',
    gymId: 'gym-powerfit-01',
    userId: 'user-owner-01',
    userName: 'Rajesh Patel',
    userRole: 'gym_owner',
    action: 'ASSIGN_TRAINER',
    entity: 'trainer',
    entityId: 'trainer-01',
    details: 'Assigned Trainer Vikram Singh to member Sneha Patil',
    timestamp: `${getOffsetDate(-12)}T14:00:00Z`,
  },
];

// Initial WhatsApp Templates
export const INITIAL_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-expiry',
    gymId: 'gym-powerfit-01',
    name: 'Membership Expiry Alert',
    category: 'membership_expiry',
    body: 'Hi {{memberName}}! 👋 Your gym membership at {{gymName}} expires on {{expiryDate}}. Renew today to keep up your fitness momentum without break! Contact us or reply here to renew.',
    isAutomated: false,
  },
  {
    id: 'tpl-payment',
    gymId: 'gym-powerfit-01',
    name: 'Fee Balance Reminder',
    category: 'payment_reminder',
    body: 'Dear {{memberName}}, this is a friendly reminder from {{gymName}} regarding your pending balance of {{amount}}. Kindly clear this at reception at your next visit or via UPI. Thank you!',
    isAutomated: false,
  },
  {
    id: 'tpl-welcome',
    gymId: 'gym-powerfit-01',
    name: 'Welcome to FitManage Gym',
    category: 'welcome_message',
    body: 'Welcome to {{gymName}}, {{memberName}}! 🎉 Your Member ID is {{memberId}}. Your trainer {{trainerName}} and our team are excited to help you smash your fitness goals! Let us know if you need anything.',
    isAutomated: false,
  },
  {
    id: 'tpl-inactive',
    gymId: 'gym-powerfit-01',
    name: 'We Miss You! (Inactive Check-in)',
    category: 'inactive_member',
    body: 'Hey {{memberName}}! We noticed you haven\'t visited {{gymName}} recently. Is everything okay? Remember, consistency is key to your progress. Drop by today for a quick energizing workout! 💪',
    isAutomated: false,
  },
  {
    id: 'tpl-renewal',
    gymId: 'gym-powerfit-01',
    name: 'Membership Renewed Confirmation',
    category: 'renewal',
    body: 'Thank you for renewing your membership with {{gymName}}, {{memberName}}! Your membership has been extended to {{expiryDate}}. Let\'s achieve greater milestones together! 🔥',
    isAutomated: false,
  },
];

// Initial App Notifications
export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    gymId: 'gym-powerfit-01',
    type: 'membership_expiring',
    title: 'Membership Expiring Soon',
    message: 'Amit Verma\'s monthly membership expires in 2 days.',
    entityId: 'mem-002',
    isRead: false,
    createdAt: `${getOffsetDate(0)}T08:00:00Z`,
  },
  {
    id: 'notif-02',
    gymId: 'gym-powerfit-01',
    type: 'payment_pending',
    title: 'Pending Fee Balance',
    message: 'Sneha Patil has an outstanding fee balance of ₹2,000.',
    entityId: 'mem-003',
    isRead: false,
    createdAt: `${getOffsetDate(-1)}T14:30:00Z`,
  },
  {
    id: 'notif-03',
    gymId: 'gym-powerfit-01',
    type: 'attendance',
    title: 'Inactivity Alert',
    message: 'Vikram Desai has not visited for 16 days. Consider sending a WhatsApp check-in.',
    entityId: 'mem-006',
    isRead: false,
    createdAt: `${getOffsetDate(-1)}T17:00:00Z`,
  },
  {
    id: 'notif-04',
    gymId: 'gym-powerfit-01',
    type: 'membership_expiring',
    title: 'Membership Expired',
    message: 'Karan Malhotra\'s half-yearly membership expired 10 days ago.',
    entityId: 'mem-004',
    isRead: true,
    createdAt: `${getOffsetDate(-2)}T09:00:00Z`,
  },
];
