import {
  Gym,
  User,
  MembershipPlan,
  Trainer,
  Member,
  PaymentRecord,
  AttendanceRecord,
  WorkoutPlan,
  DietPlan,
  ProgressRecord,
  AuditLog,
  AppNotification,
} from '../types';

export const INITIAL_GYMS: Gym[] = [
  {
    id: 'gym_powerfit',
    name: 'PowerFit Arena',
    slug: 'powerfit-arena',
    ownerId: 'usr_owner',
    ownerName: 'Vikram Sharma',
    ownerEmail: 'vikram@powerfit.com',
    ownerPhone: '+91 98765 43210',
    phone: '+91 98765 43210',
    email: 'vikram@powerfit.com',
    address: 'Plot 42, Cyber Hub Rd, Sector 29, Gurugram, HR',
    status: 'active',
    planTier: 'pro',
    isOnboarded: true,
    settings: {
      name: 'PowerFit Arena',
      tagline: 'Elite Strength & High Performance Center',
      logoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=150&auto=format&fit=crop&q=80',
      address: 'Plot 42, Cyber Hub Rd, Sector 29, Gurugram, HR',
      phone: '+91 98765 43210',
      email: 'vikram@powerfit.com',
      website: 'https://powerfitarena.com',
      currency: 'INR',
      currencySymbol: '₹',
      timezone: 'Asia/Kolkata',
      receiptPrefix: 'REC',
      memberIdPrefix: 'FIT',
      expiringSoonDays: 7,
      duplicateAttendanceMinutes: 45,
      enableQrAttendance: true,
      theme: 'light',
    },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_owner',
    name: 'Vikram Sharma',
    email: 'vikram@powerfit.com',
    role: 'gym_owner',
    gymId: 'gym_powerfit',
    phone: '+91 98765 43210',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'usr_staff',
    name: 'Pooja Verma',
    email: 'pooja@powerfit.com',
    role: 'staff',
    gymId: 'gym_powerfit',
    phone: '+91 98111 22233',
    status: 'active',
    createdAt: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'usr_trainer',
    name: 'Arjun Kapoor',
    email: 'arjun@powerfit.com',
    role: 'trainer',
    gymId: 'gym_powerfit',
    phone: '+91 98222 33445',
    status: 'active',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'usr_member',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@gmail.com',
    role: 'member',
    gymId: 'gym_powerfit',
    phone: '+91 98765 11111',
    status: 'active',
    createdAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'usr_admin',
    name: 'Platform SuperAdmin',
    email: 'admin@fitmanage.com',
    role: 'super_admin',
    phone: '+91 99999 00000',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_PLANS: MembershipPlan[] = [
  {
    id: 'plan_monthly',
    gymId: 'gym_powerfit',
    name: 'Monthly Strength Access',
    durationMonths: 1,
    price: 1999,
    admissionFee: 500,
    description: 'Full access to weight room, functional turf, and standard lockers.',
    popular: false,
    isActive: true,
    features: ['Full Gym Floor', 'Locker Room Access', 'Cardio Zone', 'Water Bar'],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'plan_quarterly',
    gymId: 'gym_powerfit',
    name: 'Quarterly Transformation',
    durationMonths: 3,
    price: 4999,
    admissionFee: 0,
    description: '3 months unlimited access with body assessment and steam bath.',
    popular: true,
    isActive: true,
    features: ['Full Gym Floor', 'Steam & Sauna', '1 PT Assessment', 'Custom Diet Chart'],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'plan_annual',
    gymId: 'gym_powerfit',
    name: 'Annual Elite VIP',
    durationMonths: 12,
    price: 14999,
    admissionFee: 0,
    description: '365 days VIP access with 4 guest passes and free locker.',
    popular: false,
    isActive: true,
    features: ['Unlimited 24/7 Access', 'All Group Classes', 'Sauna & Steam', 'Free Assigned Locker', 'Quarterly DEXA Scan'],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'trn_arjun',
    gymId: 'gym_powerfit',
    name: 'Arjun Kapoor',
    phone: '+91 98222 33445',
    email: 'arjun@powerfit.com',
    specialization: 'CrossFit & Hypertrophy',
    experienceYears: 6,
    shift: 'morning',
    rating: 4.9,
    status: 'active',
    photo: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'trn_sneha',
    gymId: 'gym_powerfit',
    name: 'Sneha Patel',
    phone: '+91 98333 44556',
    email: 'sneha@powerfit.com',
    specialization: 'Yoga & Core Mobility',
    experienceYears: 4,
    shift: 'evening',
    rating: 4.8,
    status: 'active',
    photo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T00:00:00.000Z',
  },
];

const today = new Date();
const formatDate = (daysOffset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem_rahul',
    gymId: 'gym_powerfit',
    memberCode: 'FIT-000001',
    qrToken: 'FIT_FIT-000001_QR_TOKEN',
    firstName: 'Rahul',
    lastName: 'Mehta',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1995-04-12',
    phone: '+91 98765 11111',
    whatsappNumber: '+91 98765 11111',
    email: 'rahul.mehta@gmail.com',
    address: 'A-402 Nirvana Country, Gurugram',
    emergencyContactName: 'Ravi Mehta',
    emergencyContactPhone: '+91 98765 99991',
    notes: 'Pre-existing mild lumbar strain, focuses on core strength',
    currentPlanId: 'plan_quarterly',
    currentPlanName: 'Quarterly Transformation',
    membershipStartDate: formatDate(-20),
    membershipEndDate: formatDate(70),
    durationMonths: 3,
    membershipPrice: 4999,
    discount: 0,
    finalAmount: 4999,
    totalPaid: 4999,
    balanceDue: 0,
    primaryTrainerId: 'trn_arjun',
    primaryTrainerName: 'Arjun Kapoor',
    status: 'active',
    isArchived: false,
    totalVisits: 14,
    lastVisitDate: formatDate(0),
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'mem_ananya',
    gymId: 'gym_powerfit',
    memberCode: 'FIT-000002',
    qrToken: 'FIT_FIT-000002_QR_TOKEN',
    firstName: 'Ananya',
    lastName: 'Iyer',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dateOfBirth: '1998-09-22',
    phone: '+91 98765 22222',
    whatsappNumber: '+91 98765 22222',
    email: 'ananya.iyer@gmail.com',
    address: 'Villa 12, Palm Springs, Gurugram',
    emergencyContactName: 'Kavita Iyer',
    emergencyContactPhone: '+91 98765 99992',
    notes: 'Prepares for half marathon in November',
    currentPlanId: 'plan_quarterly',
    currentPlanName: 'Quarterly Transformation',
    membershipStartDate: formatDate(-85),
    membershipEndDate: formatDate(5), // Expiring soon!
    durationMonths: 3,
    membershipPrice: 4999,
    discount: 0,
    finalAmount: 4999,
    totalPaid: 4999,
    balanceDue: 0,
    primaryTrainerId: 'trn_sneha',
    primaryTrainerName: 'Sneha Patel',
    status: 'expiring_soon',
    isArchived: false,
    totalVisits: 32,
    lastVisitDate: formatDate(-1),
    createdAt: '2025-11-20T10:00:00.000Z',
    updatedAt: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'mem_rohit',
    gymId: 'gym_powerfit',
    memberCode: 'FIT-000003',
    qrToken: 'FIT_FIT-000003_QR_TOKEN',
    firstName: 'Rohit',
    lastName: 'Chopra',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dateOfBirth: '1992-12-05',
    phone: '+91 98765 33333',
    whatsappNumber: '+91 98765 33333',
    email: 'rohit.c@gmail.com',
    address: 'Flat 101, Galaxy Towers, Sector 45',
    emergencyContactName: 'Sunita Chopra',
    emergencyContactPhone: '+91 98765 99993',
    notes: 'Membership expired last week - contacted for renewal',
    currentPlanId: 'plan_monthly',
    currentPlanName: 'Monthly Strength Access',
    membershipStartDate: formatDate(-40),
    membershipEndDate: formatDate(-10), // Expired!
    durationMonths: 1,
    membershipPrice: 1999,
    discount: 0,
    finalAmount: 1999,
    totalPaid: 1999,
    balanceDue: 0,
    status: 'expired',
    isArchived: false,
    totalVisits: 18,
    lastVisitDate: formatDate(-12),
    createdAt: '2026-01-05T10:00:00.000Z',
    updatedAt: '2026-02-20T10:00:00.000Z',
  },
  {
    id: 'mem_priya',
    gymId: 'gym_powerfit',
    memberCode: 'FIT-000004',
    qrToken: 'FIT_FIT-000004_QR_TOKEN',
    firstName: 'Priya',
    lastName: 'Nair',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dateOfBirth: '1996-07-18',
    phone: '+91 98765 44444',
    whatsappNumber: '+91 98765 44444',
    email: 'priya.nair@gmail.com',
    address: 'Penthouse 3, DLF Phase 5',
    emergencyContactName: 'Deepak Nair',
    emergencyContactPhone: '+91 98765 99994',
    notes: 'Annual membership with partial balance remaining',
    currentPlanId: 'plan_annual',
    currentPlanName: 'Annual Elite VIP',
    membershipStartDate: formatDate(-10),
    membershipEndDate: formatDate(355),
    durationMonths: 12,
    membershipPrice: 14999,
    discount: 0,
    finalAmount: 14999,
    totalPaid: 10000,
    balanceDue: 4999, // Balance pending!
    status: 'active',
    isArchived: false,
    totalVisits: 8,
    lastVisitDate: formatDate(0),
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-10T10:00:00.000Z',
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay_001',
    gymId: 'gym_powerfit',
    receiptNumber: 'REC-2026-000001',
    memberId: 'mem_rahul',
    memberName: 'Rahul Mehta',
    memberCode: 'FIT-000001',
    planId: 'plan_quarterly',
    planName: 'Quarterly Transformation',
    amount: 4999,
    paymentMethod: 'upi',
    paymentDate: formatDate(-20),
    referenceNumber: 'UPI/9876543210/PAY1',
    collectedByUserName: 'Pooja Verma',
    balanceRemaining: 0,
    notes: 'Registration payment via GPay UPI',
    status: 'completed',
    createdAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 'pay_002',
    gymId: 'gym_powerfit',
    receiptNumber: 'REC-2026-000002',
    memberId: 'mem_priya',
    memberName: 'Priya Nair',
    memberCode: 'FIT-000004',
    planId: 'plan_annual',
    planName: 'Annual Elite VIP',
    amount: 10000,
    paymentMethod: 'card',
    paymentDate: formatDate(-10),
    referenceNumber: 'HDFC_POS_8821',
    collectedByUserName: 'Vikram Sharma',
    balanceRemaining: 4999,
    notes: 'Part payment for Annual Elite VIP',
    status: 'completed',
    createdAt: '2026-02-10T10:00:00.000Z',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att_001',
    gymId: 'gym_powerfit',
    memberId: 'mem_rahul',
    memberName: 'Rahul Mehta',
    memberCode: 'FIT-000001',
    date: formatDate(0),
    time: '07:15 AM',
    checkInTime: '07:15 AM',
    method: 'qr_code',
    checkInMethod: 'qr_code',
    staffName: 'Reception QR Scanner',
    status: 'present',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'att_002',
    gymId: 'gym_powerfit',
    memberId: 'mem_priya',
    memberName: 'Priya Nair',
    memberCode: 'FIT-000004',
    date: formatDate(0),
    time: '08:30 AM',
    checkInTime: '08:30 AM',
    method: 'manual',
    checkInMethod: 'manual',
    staffName: 'Pooja Verma',
    status: 'present',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_WORKOUTS: WorkoutPlan[] = [
  {
    id: 'wo_001',
    gymId: 'gym_powerfit',
    name: 'Push Pull Legs (PPL) Hypertrophy',
    goal: 'Muscle Hypertrophy & Strength',
    level: 'intermediate',
    daysPerWeek: 6,
    durationWeeks: 12,
    description: 'Gold standard 6-day split focusing on compound and isolation progression.',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DIETS: DietPlan[] = [
  {
    id: 'diet_001',
    gymId: 'gym_powerfit',
    name: 'Lean Muscle Gain (2400 kcal)',
    goal: 'Lean Muscle & Recovery',
    dailyCalories: 2400,
    description: 'High protein split with 160g protein, complex carbohydrates, and essential omega-3s.',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_PROGRESS: ProgressRecord[] = [
  {
    id: 'prog_001',
    gymId: 'gym_powerfit',
    memberId: 'mem_rahul',
    date: formatDate(-20),
    weightKg: 82.5,
    heightCm: 178,
    chestInches: 41,
    waistInches: 34,
    bicepsInches: 14.5,
    bodyFatPercent: 18.2,
    notes: 'Initial joining baseline assessment',
    createdAt: '2026-02-01T10:00:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_001',
    gymId: 'gym_powerfit',
    userId: 'usr_owner',
    userName: 'Vikram Sharma',
    userRole: 'gym_owner',
    action: 'INIT_SYSTEM',
    entity: 'system',
    entityId: 'gym_powerfit',
    details: 'System initialized with Hostinger MySQL architecture support',
    timestamp: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_001',
    gymId: 'gym_powerfit',
    type: 'system',
    title: 'Hostinger MySQL Ready',
    message: 'FitManage is configured with Hostinger MySQL support. You can configure Hostinger credentials in Settings.',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
];
